### ISSUE TITLE
most conduits disappear on relog

### ISSUE THREAD

**Issue by MrMirajIzHere** [MartinSVK12/signalindustries#12]
bta 7.1
no extra mods

1. place conduits
2. exit the world and join back

![Скриншот 06-05-2024 221143](https://github.com/MartinSVK12/signalindustries/assets/106516237/4bb5c28d-5a51-4549-8baf-4647729d64f4)
![Скриншот 06-05-2024 221201](https://github.com/MartinSVK12/signalindustries/assets/106516237/5bd75eae-0b65-4736-b4d5-72a01df615c5)
![Скриншот 06-05-2024 222052](https://github.com/MartinSVK12/signalindustries/assets/106516237/c8c8011f-ac74-4d96-9190-43817632f28c)

**Comment by MartinSVK12** [comment]
This is a known issue and will be fixed in the next release.

**Comment by MartinSVK12** [comment]
Should be fixed in 0.8.0.
