### ISSUE TITLE
Multiplayer server doesn't start with signal industries

### ISSUE THREAD

**Issue by Chackapon** [MartinSVK12/signalindustries#18]
BTA version: 7.2_01
Signal Industries: 0.17.0
Catalyst: All 1.11.0

[latest.log](https://github.com/user-attachments/files/17635340/latest.log)

As soon as I try to launch the server with signal industries present it won't start at all. It does start with just catalyst present. I tried to remove battletowers which is mentioned in the log but then another mod can't start because of signal industries, back to the foodture, so I suspect the problem is caused by SI mod

**Comment by MartinSVK12** [comment]
Multiplayer is not supported yet.
